name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest]
        go: ['1.21', '1.22']

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Go ${{matrix.go}}

    steps:
    - uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        check-latest: true

    - name: Show Go Version and environment
      run: |
        go version
        go env

    - name: Install dependencies
      run: |
        sudo apt install golint
        GOBIN=$HOME/.local/bin go install honnef.co/go/tools/cmd/staticcheck@2023.1.6
        make

    - name: Run tests
      run: |
        make test
